<?php

$this->css = array(
    'css/codepad.css'
);

$this->js = array(
    'js/ace/ace.js',
    'js/codepad.js'
);

?>
<div class="container-fluid">
    <div class="row-fluid">
        <div id="alert" class="alert alert-block hide">
        </div>
    </div>
    <div class="row-fluid">
        <div class="form-inline">
            <input id="codepadSaveActionSnippetInput" class="input-medium" type="text" placeholder="Snippet...">
            <select id="codepadSaveActionThemeInput">
                <option value="">Thème...</option>
                <?php foreach ($this->themes as $name => $theme): ?>
                    <option><?php echo htmlspecialchars($name); ?></option>
                <?php endforeach; ?>
            </select>
            <button id="codepadSaveActionSubmitButton" type="submit" class="btn btn-success">Enregistrer</button>
        </div>
    </div>
    <hr>
    <div id="codepadContainer" class="row-fluid">
        <div id="codepadEditorContainer" class="span6 well">
            <div id="codepadEditor"></div>
        </div>
        <div id="codepadResultContainer" class="span6 well">
        </div>
    </div>
</div>
