<?php

$this->css = array(
    'css/codepad.css'
);

$this->js = array(
    'js/ace/ace.js',
    'js/alert.js',
    'js/codepad.js'
);

?>
<div class="container-fluid">
    <div class="row-fluid">
        <div id="alert" class="alert alert-block hide">
        </div>
    </div>
    <div class="row-fluid">
        <div class="form-inline">
            <input id="codepadSaveActionSnippetInput"
                class="input-medium"
                type="text"
                placeholder="Snippet..."
                <?php if (isset($this->snippet)): ?>
                    value="<?php echo htmlspecialchars($this->snippet); ?>"
                <?php endif; ?>
            >
            <select id="codepadSaveActionThemeInput">
                <option value="">Thème...</option>
                <?php foreach ($this->themes as $name => $theme): ?>
                    <option
                        <?php if (isset($this->theme) && $name === $this->theme): ?>
                            selected="selected"
                        <?php endif; ?>
                    >
                        <?php echo htmlspecialchars($name); ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <button id="codepadSaveActionSubmitButton" type="submit" class="btn btn-success">Enregistrer</button>
        </div>
    </div>
    <hr>
    <div id="codepadContainer" class="row-fluid">
        <div id="codepadEditorContainer" class="span6 well">
            <div id="codepadEditor"><?php echo htmlspecialchars($this->code); ?></div>
        </div>
        <iframe
            id="codepadResultFrame"
            class="span6 well"
            sandbox="allow-forms allow-scripts"
            <?php if (null !== $this->code): ?>
                src="index.php?controller=codepad&amp;action=eval&amp;code=<?php echo urlencode($this->code); ?>"
            <?php endif; ?>
        >
        </iframe>
    </div>
</div>
