<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Certime</title>
    <meta name="author" content="Ludovic Fabrèges">
    <link href="css/bootstrap.css" rel="stylesheet">
    <link href="css/certime.css" rel="stylesheet">
    <?php if (is_array($this->css) || $this->css instanceof \Traversable):
        foreach ($this->css as $css): ?>
            <link href="<?php echo $css; ?>" rel="stylesheet">
        <?php endforeach;
    endif; ?>
    <!--[if lt IE 9]>
        <script src="js/html5.js"></script>
    <![endif]-->
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container-fluid">
                <a class="brand" href="index.php">Certime</a>
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <?php foreach (
                            array(
                                'repository' => 'Dépôt',
                                'codepad' => 'Codepad'
                            )
                            as $controller => $title):
                        ?>
                            <li
                                <?php if ($controller === $this->page): ?>
                                    class="active"
                                <?php endif; ?>
                            >
                                <a href="index.php?controller=<?php echo $controller; ?>">
                                    <?php echo $title; ?>
                                </a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <?php echo $this->content; ?>
    <script src="js/jquery.js"></script>
    <script src="js/bootstrap.js"></script>
    <?php if (is_array($this->js) || $this->js instanceof \Traversable):
        foreach ($this->js as $js): ?>
            <script src="<?php echo $js; ?>"></script>
        <?php endforeach;
    endif; ?>
</body>
</html>